config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students do
    resources :addresses
  end
  resources :courses, only: :show
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
  validates_presence_of :description, :street, :city, :state, :zip_code
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates_presence_of(:title)
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    student = Student.find(params[:student_id])
    student.addresses.create(address_params)
    redirect_to student_path(student)
  end

  private
  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zip_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create!(student_params)
    redirect_to student_path(student)
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.find(params[:id])
    student.update(student_params)
    redirect_to student_path(student)
  end

  def destroy
    Student.destroy(params[:id])
    redirect_to students_path
  end


  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>Add a New Address for <%= @student.name %></h1>

<%= form_for [ @student, @address ] do |f| %>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :street %><br/>
    <%= f.text_field :street %>
  </p>
  <p>
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br/>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %><br/>
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.submit 'submit' %>
  </p>
<% end %>

app/views/courses/show.html.erb
<h1> <%= @course.title %></h1>

<% @course.students.each do |student| %>
   <p><%= student.name %></p>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div>
      <%= link_to 'All Students', students_path %>
      <%= link_to 'Create A New Student', new_student_path %>
    </div>
    </br>
    </br>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit <%= @student.name %></h1>
<%= form_for(@student) do |f| %>
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.submit 'submit' %>
</p>
<% end %>

app/views/students/index.html.erb
<h1> All Students </h1>
<% @students.each do |student| %>
  <%=link_to student.name, student_path(student) %>

  <% end %>

app/views/students/new.html.erb
<h1>Create a New Student</h1>
<%= form_for(@student) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'submit' %>
  </p>
<% end %>

app/views/students/show.html.erb
<h1> <%= @student.name %></h1>
<% @student.addresses.each do |address| %>
  <ul>
      <li><%= address.description %></li>
      <li><%= address.street %></li>
      <li><%= address.city %></li>
      <li><%= address.state %></li>
      <li><%= address.zip_code %></li>
  </ul>
  <% end %>
<% @student.courses.each do |course| %>
  <p><%= course.title %></p>
<% end %>
<%= link_to 'Delete', student_path(@student), method: :delete %>